"""§ JARVIS Implementation Master Plan — PASSAGGIO 13 §G/§P/§Q. The Python
mirror of `core/semantic/embedding/TextPreprocessor.kt` — SAME three steps,
SAME order: NFC Unicode normalization, trim, collapse-whitespace. Casing is
never altered.

Both sides implement the SAME published algorithm (Unicode Standard Annex
#15 NFC — `unicodedata.normalize` here, `java.text.Normalizer` on the Kotlin
side), not two independently-guessed behaviors, so cross-language parity is
a well-founded claim (see `TextPreprocessor.kt`'s own doc comment).

`__main__` re-verifies every vector in `preprocessing_golden.json` (the
SAME fixture `TextPreprocessorTest.kt` loads) against a FRESH run of
`canonicalize()` here — genuine self-consistency, not just "the file was
generated by this same function once".
"""
from __future__ import annotations

import re
import unicodedata

_WHITESPACE_RE = re.compile(r"\s+")


def canonicalize(text: str) -> str:
    """Canonicalizes `text` per `SemanticEncoderContract.CURRENT`:
    1. NFC Unicode normalization.
    2. Trim leading/trailing whitespace.
    3. Collapse any run of Unicode whitespace to a single ASCII space.
    Casing is deliberately never altered (`casingPolicy = "PRESERVE"`).
    """
    normalized = unicodedata.normalize("NFC", text)
    trimmed = normalized.strip()
    return _WHITESPACE_RE.sub(" ", trimmed)


if __name__ == "__main__":
    import json
    import os

    fixture_path = os.path.join(
        os.path.dirname(__file__), "..", "..", "core", "src", "test", "resources",
        "semantic", "preprocessing_golden.json",
    )
    with open(fixture_path, encoding="utf-8") as f:
        fixture = json.load(f)

    failures = []
    for vector in fixture["vectors"]:
        actual = canonicalize(vector["input"])
        expected = vector["expectedCanonical"]
        status = "OK" if actual == expected else "MISMATCH"
        if actual != expected:
            failures.append(vector["name"])
        print(f"{status:8} {vector['name']}: {actual!r}")

    if failures:
        raise SystemExit(f"preprocessing parity FAILED for: {failures}")
    print(f"\nAll {len(fixture['vectors'])} golden vectors match — Python re-verified against its own fixture.")
