package com.simone.jarvismobile.responsibility

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

/**
 * § JARVIS — PERSISTENT AGENT KERNEL — PA-1A. Reproduces the pattern
 * `com.simone.jarvismobile.proactive.TriggerEvidenceMigrationRegressionTest`
 * established after MICRO-PATCH E.1: an in-place upgrade from a real,
 * previously-installed schema (version 14 — before either Responsibility
 * table existed) through the real
 * [ResponsibilityMigrations.MIGRATION_14_15] must open cleanly and pass
 * Room's own schema validation (`onValidateSchema`), including the
 * `agent_responsibility_journal` table's `key`/`atMs` indices — a mismatch
 * there would throw on the very first open of the whole shared database
 * after migrating through this step, exactly like the proven
 * `trigger_evidence` bug this pattern exists to catch a repeat of.
 *
 * Deliberately a small, standalone `@Database` scoped to just these two
 * entities — not the full `JarvisDatabase` — so this test exercises exactly
 * the migration/entity pair under test without needing to reconstruct the
 * other ~16 tables' full historical schema by hand. No `room-testing`/
 * `MigrationTestHelper` dependency needed: the raw pre-migration file is
 * built with plain framework SQLite (`Context.openOrCreateDatabase`),
 * matching exactly what a real device's file looks like at that schema
 * version.
 */
@Database(
    entities = [ResponsibilityEntity::class, ResponsibilityJournalRowEntity::class],
    version = 15,
    exportSchema = false,
)
internal abstract class ResponsibilityOnlyTestDatabase : RoomDatabase() {
    abstract fun responsibilityDao(): ResponsibilityDao
    abstract fun responsibilityJournalDao(): ResponsibilityJournalDao
}

@RunWith(AndroidJUnit4::class)
class ResponsibilityMigrationRegressionTest {

    private val dbName = "responsibility_migration_regression_test.db"
    private val context: Context = ApplicationProvider.getApplicationContext()

    @After
    fun cleanup() {
        context.deleteDatabase(dbName)
    }

    @Test
    fun realMigration14To15_opensAndValidatesAgainstTheEntitiesItCreates() {
        // Simulate a real device's file at schema version 14: neither table
        // this migration is responsible for creating exists yet.
        context.openOrCreateDatabase(dbName, Context.MODE_PRIVATE, null).use { raw ->
            raw.version = 14
        }

        val db = Room.databaseBuilder(context, ResponsibilityOnlyTestDatabase::class.java, dbName)
            .addMigrations(ResponsibilityMigrations.MIGRATION_14_15)
            .build()

        // Forces Room to actually open the file, run the real migration, and
        // validate the resulting schema (columns AND indices) against what
        // both @Entity annotations declare.
        val (insertedResponsibilityKey, insertedJournalId) = runBlocking {
            val responsibilityDao = db.responsibilityDao()
            val journalDao = db.responsibilityJournalDao()

            val key = "MORNING_ASSISTANCE:2026-10-01"
            val insertResult = responsibilityDao.tryInsert(
                ResponsibilityEntity(
                    logicalKey = key,
                    type = "MORNING_ASSISTANCE",
                    lifecycleState = "WAITING",
                    revision = 1L,
                    createdAtMs = 1L,
                    updatedAtMs = 1L,
                ),
            )
            assertTrue("expected the insert to succeed (not IGNORE-d as a conflict)", insertResult != -1L)

            val journalId = journalDao.insert(
                ResponsibilityJournalRowEntity(
                    atMs = 1L,
                    key = key,
                    type = "MORNING_ASSISTANCE",
                    fromState = null,
                    toState = "WAITING",
                    decision = null,
                    verificationOutcome = null,
                    reasonCode = "regression_test",
                ),
            )
            key to journalId
        }
        assertTrue("expected a valid autogenerated journal row id", insertedJournalId > 0)

        // A second open of the SAME already-migrated file must also
        // validate cleanly — this is what actually crashed in production
        // for trigger_evidence (every subsequent DAO call on the poisoned
        // instance, not just the first one).
        db.close()
        val reopened = Room.databaseBuilder(context, ResponsibilityOnlyTestDatabase::class.java, dbName)
            .addMigrations(ResponsibilityMigrations.MIGRATION_14_15)
            .build()
        val found = runBlocking { reopened.responsibilityDao().find(insertedResponsibilityKey) }
        assertEquals("WAITING", found?.lifecycleState)
        val journalRows = runBlocking { reopened.responsibilityJournalDao().recentForKey(insertedResponsibilityKey, limit = 10) }
        assertTrue("expected the previously inserted journal row to survive reopen", journalRows.isNotEmpty())
        reopened.close()
    }
}
