package com.simone.jarvismobile.proactive

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

/**
 * § JARVIS Implementation Master Plan — MICRO-PATCH E.1 §9. Reproduces the
 * EXACT proven root cause of the device cold-start/upgrade crash: a device
 * upgrading in place from a real, previously-installed schema (version 12
 * — before the `trigger_evidence` table existed) through the real
 * [TriggerEvidenceMigrations.MIGRATION_12_13] must open cleanly and pass
 * Room's own schema validation (`onValidateSchema`).
 *
 * Before this patch, [TriggerEvidenceRowEntity] declared no `indices` while
 * the migration created two (`source`, `eventAtMs`) via raw SQL — a
 * mismatch Room's validator rejects with `IllegalStateException` on the
 * FIRST open of the whole shared database after migrating through this
 * step, and on EVERY subsequent open attempt thereafter (the failure is not
 * self-healing). A clean install never exercises this path at all — Room
 * just calls `createAllTables()` from the current (already self-consistent)
 * entity shape — which is exactly why "works after a clean reinstall" can
 * never be trusted as proof this class of bug is fixed. This test forces
 * the real migration to run and fails loudly if the schema it produces
 * does not match what [TriggerEvidenceRowEntity] declares, instead of
 * silently passing on a clean-install-shaped test.
 *
 * Deliberately a small, standalone `@Database` scoped to just this one
 * entity — not the full `JarvisDatabase` — so this test exercises exactly
 * the migration/entity pair under test without needing to reconstruct the
 * other ~14 tables' full historical schema by hand. No `room-testing`/
 * `MigrationTestHelper` dependency needed: the raw pre-migration file is
 * built with plain framework SQLite (`Context.openOrCreateDatabase`),
 * matching exactly what a real device's file looks like at that schema
 * version.
 */
@Database(entities = [TriggerEvidenceRowEntity::class], version = 13, exportSchema = false)
internal abstract class TriggerEvidenceOnlyTestDatabase : RoomDatabase() {
    abstract fun dao(): TriggerEvidenceDao
}

@RunWith(AndroidJUnit4::class)
class TriggerEvidenceMigrationRegressionTest {

    private val dbName = "trigger_evidence_migration_regression_test.db"
    private val context: Context = ApplicationProvider.getApplicationContext()

    @After
    fun cleanup() {
        context.deleteDatabase(dbName)
    }

    @Test
    fun realMigration12To13_opensAndValidatesAgainstTheEntityItCreates() {
        // Simulate a real device's file at schema version 12: the table
        // this migration is responsible for creating does not exist yet.
        context.openOrCreateDatabase(dbName, Context.MODE_PRIVATE, null).use { raw ->
            raw.version = 12
        }

        val db = Room.databaseBuilder(context, TriggerEvidenceOnlyTestDatabase::class.java, dbName)
            .addMigrations(TriggerEvidenceMigrations.MIGRATION_12_13)
            .build()

        // Forces Room to actually open the file, run the real migration,
        // and validate the resulting schema — the exact call that threw
        // IllegalStateException on a real device before this patch's fix.
        val insertedId = runBlocking {
            db.dao().insert(
                TriggerEvidenceRowEntity(
                    eventAtMs = 1L,
                    processSessionId = "regression-test",
                    source = "FIRST_UNLOCK",
                    stage = "SERVICE_ON_CREATE",
                    detail = null,
                ),
            )
        }
        assertTrue("expected a valid autogenerated row id", insertedId > 0)

        // A second open of the SAME already-migrated file must also
        // validate cleanly — this is what actually crashed in production
        // (every subsequent DAO call on the poisoned instance, not just
        // the first one).
        db.close()
        val reopened = Room.databaseBuilder(context, TriggerEvidenceOnlyTestDatabase::class.java, dbName)
            .addMigrations(TriggerEvidenceMigrations.MIGRATION_12_13)
            .build()
        val rows = runBlocking { reopened.dao().recentAll(limit = 10) }
        assertTrue("expected the previously inserted row to survive reopen", rows.isNotEmpty())
        reopened.close()
    }
}
